const SHOW_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';

const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

const REMOVE_USER = 'REMOVE_USER';

const HANDLE_CHANGE = 'HANDLE_CHANGE';

const GET_CLASS_BEGIN = 'GET_CLASS_BEGIN';
const GET_CLASS_SUCCESS = 'GET_CLASS_SUCCESS';
const GET_CLASS_ERROR = 'GET_CLASS_ERROR';

const CREATE_CLASS_BEGIN = 'CREATE_CLASS_BEGIN';
const CREATE_CLASS_SUCCESS = 'CREATE_CLASS_SUCCESS';
const CREATE_CLASS_ERROR = 'CREATE_CLASS_ERROR';

export {
  SHOW_ALERT,
  CLEAR_ALERT,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  LOGIN_USER_BEGIN,
  TOGGLE_SIDEBAR,
  REMOVE_USER,
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  HANDLE_CHANGE,
  GET_CLASS_ERROR,
  GET_CLASS_SUCCESS,
  GET_CLASS_BEGIN,
  CREATE_CLASS_ERROR,
  CREATE_CLASS_SUCCESS,
  CREATE_CLASS_BEGIN,
};
