const SHOW_ALERT = 'SHOW_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';

const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export {
  SHOW_ALERT,
  CLEAR_ALERT,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  LOGIN_USER_BEGIN,
  TOGGLE_SIDEBAR,
};
